#! /bin/bash
#
# httpd   Start/Stop the Apache httpd Server
#
# chkconfig: 2345 90 60
# description: httpd is the Apache httpd Server
# processname: httpd
# config: /etc/httpd/conf/httpd.conf
# pidfile: /var/run/httpd/httpd.pid

user=cyg_server
group=SYSTEM
PATH=/sbin:/usr/sbin:/usr/bin
PREFIX=/usr
CONFIG=/etc/httpd/conf/httpd.conf
PIDFILE=/var/run/httpd/httpd.pid
LOGFILE=/var/log/httpd.log
LOGDIR=/var/log/httpd

# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
fi

RETVAL=0

# See how we were called.

prog="httpd"
progdir="/usr/sbin"
program="$progdir/$prog.exe"

test -f $program || exit 0

# Source configuration
if [ -f /etc/sysconfig/$prog ] ; then
    . /etc/sysconfig/$prog
fi

start() {
	echo -n $"Starting $prog: "
	# check if cygrunsrv process
	cygrunsrv --start $prog
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $PIDFILE  && echo "done."
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	cygrunsrv --stop $prog
	if test -r $PIDFILE; then
	    kill `cat $PIDFILE` 2> /dev/null || echo -n " failed"
	else
	    echo -n " no PID file"
	fi
	# this really needs a long time to stop.
	RETVAL=$?
	echo "."
	[ $RETVAL -eq 0 ] && rm -f $PIDFILE && echo "done."
	return $RETVAL
}

rhstatus() {
	# service status
	cygrunsrv -Q $prog
	/usr/sbin/apachectl status
}

restart() {
	echo -n $"Restarting $prog: "
	$0 stop
	sleep 1
	$0 start
	echo "done."
}

install() {
	echo -n $"Installing $prog program: "
	# some safety measures
	rm -fr $LOGDIR/*
	touch $LOGFILE $PIDFILE
	chmod g+w $LOGFILE $PIDFILE	
	# hack: fix for uid=18 (SYSTEM)!
	chgrp $group $LOGFILE $PIDFILE
	chown $user $LOGFILE $PIDFILE
	# it was compiled with user=18 (SYSTEM)
	
	cygrunsrv -I "${prog}" -d "CYGWIN ${prog}" -p "${program}" -u "${user}" -e "CYGWIN=binmode tty" -a "-DNO_DETACH -k start" 
	echo "done."
}
uninstall() {
	rm -fr $LOGDIR/*
	rm -f $LOGFILE $PIDFILE
	echo -n $"Uninstalling $prog program: "
	stop
	cygrunsrv --remove $prog
	echo "done."
}
reload() {
	echo -n $"Reloading $prog daemon configuration: "
	echo "unsupported. $0 restart"
	return 1

	/usr/bin/kill -HUP `cat $PIDFILE`
	RETVAL=$?
	[ $RETVAL -eq 0 ] && echo "done."
	RETVAL=$?
	return $RETVAL
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload)
	reload
	;;
  install)
	install
	;;
  uninstall)
	uninstall
	;;
  status)
	rhstatus
	;;
  condrestart)
	[ -f $PIDFILE ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|install|uninstall|restart|condrestart}"
	exit 1
esac

exit $?
